config/routes.rb
DigitalObjecIdentifier::Application.routes.draw do
  
    resources :digital_object_identifiers do
      resources :urls, only: :create
      resources :comments, only: :create
    end

  devise_for :users

  root :to => "home#index"

  resources :users
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :digital_object_identifier
	belongs_to :user

	validates :comment, presence: true, length: { maximum: 255 }
	validates :digital_object_identifier_id, :user_id, presence: true

end

app/models/digital_object_identifier.rb
class DigitalObjectIdentifier < ActiveRecord::Base
	
	belongs_to :user
	has_many :urls, :dependent => :destroy
	has_many :comments, :dependent => :destroy

	accepts_nested_attributes_for :urls, :comments

	validates :integer_identifier, presence: true, uniqueness: true, numericality: { only_integer: true }, length: { maximum: 10 }
	validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
	validates :description, presence: true, length: { maximum: 255 }
	

	def self.search(query)
    where("name like ?", query)
  end

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :digital_object_identifier
	default_scope -> { order('created_at DESC') }
  VALID_URL_REGEX = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/
  validates :url, presence: true, format: { with: VALID_URL_REGEX }, uniqueness: { case_sensitive: false } 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :digital_object_identifiers, :dependent => :destroy
  
end			

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_digital_object_identifier

	def create
		@comment = @digital_object_identifier.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			flash[:success] = "Url Added"
			redirect_to @digital_object_identifier
		end
	end

	private

	def set_digital_object_identifier
    @digital_object_identifier = DigitalObjectIdentifier.find_by( id: params[:digital_object_identifier_id])
    redirect_to root_url if @digital_object_identifier.nil?
  end

	def comment_params
		params.require(:comment).permit(:comment, :digital_object_identifier_id, :user_id )
	end

end

app/controllers/digital_object_identifiers_controller.rb
 class DigitalObjectIdentifiersController < ApplicationController
  before_action :set_digital_object_identifier, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]


  # GET /digital_object_identifiers
  # GET /digital_object_identifiers.json
  def index
    @digital_object_identifiers = DigitalObjectIdentifier.all
  end

  # GET /digital_object_identifiers/1
  # GET /digital_object_identifiers/1.json
  def show
      @url = @digital_object_identifier.urls.build
      @comment = @digital_object_identifier.comments.build  #(params[:comment].merge(:user_id => current_user.id))
  end

  # GET /digital_object_identifiers/new
  def new
    @digital_object_identifier = current_user.digital_object_identifiers.build
    @digital_object_identifier.urls << Url.new

  end

  # GET /digital_object_identifiers/1/edit
  def edit
  end

  # POST /digital_object_identifiers
  # POST /digital_object_identifiers.json
  def create
    @digital_object_identifier = current_user.digital_object_identifiers.create(digital_object_identifier_params)

    respond_to do |format|
      if @digital_object_identifier.save
        format.html { redirect_to @digital_object_identifier, notice: 'Digital object identifier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @digital_object_identifier }
      else
        format.html { render action: 'new' }
        format.json { render json: @digital_object_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /digital_object_identifiers/1
  # PATCH/PUT /digital_object_identifiers/1.json
  def update
    respond_to do |format|
      if @digital_object_identifier.update(edit_digital_object_identifier_params)
        format.html { redirect_to @digital_object_identifier, notice: 'Digital object identifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @digital_object_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /digital_object_identifiers/1
  # DELETE /digital_object_identifiers/1.json
  def destroy
    @digital_object_identifier.destroy
    respond_to do |format|
      format.html { redirect_to digital_object_identifiers_url }
      format.json { head :no_content }
    end
  end

 
  private
    def correct_user
      @digital_object_identifier = current_user.digital_object_identifiers.find_by(id: params[:id])
      redirect_to root_url if @digital_object_identifier.nil?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_digital_object_identifier
      @digital_object_identifier = DigitalObjectIdentifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def digital_object_identifier_params
      params.require(:digital_object_identifier).permit(:name, :integer_identifier, :description, urls_attributes: [ :url ] )
    end
    

    def edit_digital_object_identifier_params
      params.require(:digital_object_identifier).permit(:name, :integer_identifier, :description )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if params[:search]
			@doi = DigitalObjectIdentifier.search(params[:search]).order("created_at DESC")
		end
	end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	before_action :set_digital_object_identifier

	def create
		@url = @digital_object_identifier.urls.build(url_params)
		if @url.save
			flash[:success] = "Url Added"
			redirect_to @digital_object_identifier
		end
	end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_digital_object_identifier
    @digital_object_identifier = current_user.digital_object_identifiers.find_by( id: params[:digital_object_identifier_id])
    redirect_to root_url if @digital_object_identifier.nil?
  end

	def url_params
      params.require(:url).permit(:url, :digital_object_identifier_id )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/digital_object_identifiers_helper.rb
module DigitalObjectIdentifiersHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/digital_object_identifiers/_form.html.erb
<%= form_for(@digital_object_identifier) do |f| %>
  <% if @digital_object_identifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@digital_object_identifier.errors.count, "error") %> prohibited this digital_object_identifier from being saved:</h2>

      <ul>
      <% @digital_object_identifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :integer_identifier %><br>
    <%= f.number_field :integer_identifier %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <% if f.object.new_record? %>
    <%= f.fields_for :urls do |url_fields| %>
      <div class="field">
         <%= f.label :url %><br>
        <%= url_fields.text_field :url %>
      </div>
    <% end %>
  <% end %> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/digital_object_identifiers/edit.html.erb
<h1>Editing digital_object_identifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @digital_object_identifier %> |
<%= link_to 'Back', digital_object_identifiers_path %>

app/views/digital_object_identifiers/index.html.erb
<h1>Listing digital_object_identifiers</h1>

<table>
  <thead>
    <tr>
      <th>String identifier</th>
      <th>Name</th>
      <th>Description</th>
      <th>Current URL</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @digital_object_identifiers.each do |digital_object_identifier| %>
      <tr>
        <td><%= digital_object_identifier.name %></td>
        <td><%= digital_object_identifier.integer_identifier %></td>
        <td><%= digital_object_identifier.description %></td>
          <% if digital_object_identifier.urls.first %>
            <td><%= digital_object_identifier.urls.first.url %></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= link_to 'Show', digital_object_identifier, :class => "button" %></td> 
          <% if digital_object_identifier.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_digital_object_identifier_path(digital_object_identifier), :class => "button secondary" %></td> 
          <td><%= link_to 'Destroy', digital_object_identifier, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button alert" %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Digital object identifier', new_digital_object_identifier_path, :class => "button success" %>

app/views/digital_object_identifiers/new.html.erb
<h1>New digital_object_identifier</h1>

<%= render 'form' %>

<%= link_to 'Back', digital_object_identifiers_path %>

app/views/digital_object_identifiers/show.html.erb
<p id="notice"><%= notice %></p>
<div class ="panel row">
<p>
  <strong>String identifier:</strong>
  <%= @digital_object_identifier.name %>
</p>

<p>
  <strong>Integer identifier:</strong>
  <%= @digital_object_identifier.integer_identifier %>
</p>

<p>
  <strong>Description:</strong>
  <%= @digital_object_identifier.description %>
</p>
</div>
<div class ="panel row">
<p>
  <strong>URL:</strong>
  <% @digital_object_identifier.urls.each do |url| %>

    <% unless url == @digital_object_identifier.urls.last %>
    	<p>
    	Url: <%= url.url %>
      </p>
      <p>
       Created At: <%= url.created_at %>
    	</p>
    <% end %>
  <% end %>
</p>


<% if @digital_object_identifier.user_id == current_user.id %>
  <section>
      <%= render 'shared/url_form' %>
  </section>
<% end %>
</div>
<div class ="panel row">
<p>
  <strong>Comments:</strong>
  <% @digital_object_identifier.comments.each do |comment| %>

  <% unless comment == @digital_object_identifier.comments.last %>
    <p>
      Comment <%= comment.id %>: <%= comment.comment %> </br>
    </p>
  <% end %>
    <% end %>

  <section>
      <%= render 'shared/comment_form' %>
  </section>

</p>
</div>
<%= link_to 'Edit', edit_digital_object_identifier_path(@digital_object_identifier) %> |
<%= link_to 'Back', digital_object_identifiers_path %>

app/views/home/index.html.erb
<div class="row">
  <div class="large-4 columns">
    <ul data-orbit>
      <li><%= image_tag("doi-coffee.jpg") %></li>
      <li><%= image_tag("mishti-doi.jpg") %></li>
      <li><%= image_tag("doi.jpg") %></li>
    </ul>
   <hr />
    <%= form_tag(root_path, :method => "get" ) do %>
	    <%= label_tag(:search, "Search For:") %>
	    <%= text_field_tag :search, params[:search], placeholder: "Search DOIs" %>
	    <button class="btn" type="submit">Search</button>
    <% end %>
    <hr />
    <% if @doi %>
    	<% if @doi.first %>
    	<div class ="panel row">
	    	<p>
				  <strong>Name:</strong>
				  <%= @doi.first.name %>
				</p>

				<p>
				  <strong>Integer identifier:</strong>
				  <%= @doi.first.integer_identifier %>
				</p>

				<p>
				  <strong>Description:</strong>
				  <%= @doi.first.description %>
				</p>
				<p>
					<% if current_user %>
				  <strong>URL:</strong>
					  <% @doi.first.urls.each do |url| %>
					  	<p>
					  	<%= url.url %>
					  	</p>
					  <% end %>
					 <% else %>
					 <%= @doi.first.urls.first.url %> 
				  <% end %>
				</p>
			</div>
			<% end %>
    <% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
	<div class= "six columns">
		
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="fixed">
  <nav class= "top-bar">
    <ul class="title-area">

      <li>
        <h2>DOI Server</h2>
      </li>
      
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

  <section class="top-bar-section">
    
    <ul class="right">
      
      
      <% if user_signed_in? %>   
        <li>
        <%= link_to 'DOIs', digital_object_identifiers_path %>
        </li>
        <li>
          <%= link_to 'Edit account', edit_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </section>
  </nav>
</div>

  <div class= "fixed-icon">
    <%=link_to image_tag("DOI-150x150.jpg", :size => "150x150", :class => "logo" ), root_path %>
  </div>
  <div class ="errors">
  <%= render 'layouts/messages' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= favicon_link_tag "DOI-150x150.jpg" %>
	<title><%= content_for?(:title) ? yield(:title) : "DOI server" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
	<%= yield(:head) %>
  </head>
 <body class="<%= controller_name %> <%= action_name %>">
  <div id="container" class="container">
    <body>
        <header>
          <%= render 'layouts/navigation' %> 
        </header>
        <div class="row">
          <div class="large-12 columns">
            <div id="main" role="main">
              <%= yield %>
            </div>
          </div>
        </div>
    <%= javascript_include_tag "application" %>
   </body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for([@digital_object_identifier, @comment]) do |f| %>
	<div class="field">
    <%= f.text_area :comment %>
  </div>
  <%= f.submit "Post New Comment", class: "button success" %>
<% end %>

app/views/shared/_url_form.html.erb
<%= form_for([@digital_object_identifier, @url]) do |f| %>
	<div class="field">
    <%= f.text_field :url %>
  </div>
  <%= f.submit "Set New Url", class: "button success" %>
<% end %>